### ISSUE TITLE
args

### ISSUE THREAD

**Issue by lawensong** [emqtt/esockd#20]
esockd_acceptor_sup  ->  esockd_acceptor
input 4 args (esockd_acceptor, start_link, [ConnSup, AcceptStatsFun, BufferTuneFun, Logger])
accept 6 args (start_link(ConnSup, AcceptStatsFun, BufTuneFun, Logger, LSock, SockFun))
where is  LSock, SockFun?

**Comment by erylee** [comment]
@lawensong, please read documents about simple_one_for_one supervisor.

**Comment by lawensong** [comment]
ok,  i get it, thank you!
