### ISSUE TITLE
format nested list

### ISSUE THREAD

**Issue by obi458** [emqtt/esockd#21]
1) format({Addr, Port}) ->
    A = maybe_ntoab(Addr),
    io_lib:format("~s:~p", [A, Port]).
better 
2) format({Addr, Port}) ->
    A = maybe_ntoab(Addr),
    lists:flatten(io_lib:format("~s:~p", [A, Port])).

cause 1) gives something like ["127.0.0.1",58,"4567"]
2) makes "127.0.0.1:4567"

**Comment by erylee** [comment]
The ‘lists:flatten’ is removed for iolist could be printed as string:

io:format(“~s”, [format({Addr, Port})]).

**Comment by obi458** [comment]
Ok, but your macro:

-define(LOG(Level, Format, Args, State),
        lager:Level("Stomp(~s): " ++ Format, [esockd_net:format(State#stomp_proto.peername) | Args])).

gives: Stomp(["127.0.0.1",58,"4567"]).....

**Comment by erylee** [comment]
You mean 'emqttd_stomp' plugin? The LOG will print:
```
10:32:26.100 [info] Stomp(127.0.0.1:57034): SEND Frame: MESSAGE
subscription:1
message-id:2
destination:/queue/test
content-type:text/plain
content-length:14
```
