### ISSUE TITLE
crashes if IPv6 client connects

### ISSUE THREAD

**Issue by terinjokes** [emqtt/esockd#24]
When an IPv6 client connects, esockd terminates the process. The error comes from [esockd_access.erl:129](https://github.com/emqtt/esockd/blob/e6c27801bb5331d064081ef6d6af291a2878038c/src/esockd_access.erl#L129) assuming an IPv4 address.

**Comment by emqplus** [comment]
Hi @terinjokes, please check the PR: https://github.com/emqtt/esockd/pull/30

The 4.0 release supports IPv6 now.
