### ISSUE TITLE
Is the Docs out dated??

### ISSUE THREAD

**Issue by zzeng4** [emqtt/esockd#32]
I found in the emqttd broker, in emqttd_client.erl, there is only one start_link/2 function, and the docs of esockd, states using a start_link/1 function instead. 

when i digged into the source code, i found esockd used the erlang:apply(M,F, [Conn|Args]), which is the start_link/2, so is the doc not updated? if not, please do it, otherwise it will make us confused.

**Comment by huangdan** [comment]
invalid issue

**Comment by emqplus** [comment]
@zzeng4, The doc is right. You can specify initial arguments for callback function, for example:

```
MFArgs = {echo_server, start_link, [Arg1, Arg2]},
esockd:open(echo, 5000, Options, MFArgs).
```

The echo_server:start_link/3 should be:
```
start_link(Conn, Arg1, Arg2) ->
    ...
```
