### ISSUE TITLE
test broken

### ISSUE THREAD

**Issue by JiffB** [emqtt/esockd#62]
Debian stable (stretch)
Erlang pkgs 20.1-1 from Erlang Solutions

Hi folks,

test is failing:

$ rebar3 ct
===> Verifying dependencies...
===> Compiling esockd
===> Compiling src/esockd_proxy_proto.erl failed
src/esockd_proxy_proto.erl:134: function parse_proxy_v1/1 undefined
src/esockd_proxy_proto.erl:136: function parse_proxy_v2/1 undefined

Jean-Yves

**Comment by emqplus** [comment]
@JiffB Fixed the test cases and move them to test/esockd_SUITE.erl

**Comment by JiffB** [comment]
On Sat, 18 Nov 2017 12:11:41 +0000 (UTC)
Feng Lee <notifications@github.com> wrote:

> @JiffB Fixed the test cases and move them to test/esockd_SUITE.erl
> 

Thanks, Feng !

JiffB
