### ISSUE TITLE
esockd as dependency by rebar3 miss .hrl file while release

### ISSUE THREAD

**Issue by haoxianhan** [emqtt/esockd#81]
I add a few deps to my project with rebar3,
I use `-include_lib("esockd/include/esockd.hrl").` to include esockd's hrl file,
after created release, I fould  lib's `esock include folder` is empty so that could not found the hrl file, I think it's not necessary for esock, does any proper way to include those hrl file???

**Comment by emqplus** [comment]
@haoxianhan Your project should not include `esockd.hrl`, for the header file is used internally, and may be changed.

**Comment by haoxianhan** [comment]
I learn from example, and just need the define `?ESOCK`, is any proper way I could use the example in my project?

**Comment by emqplus** [comment]
@haoxianhan The 'ESOCK' macro has been removed from esockd.hrl in the latest release. Please checkout the `emqx30` branch.

**Comment by haoxianhan** [comment]
Will esockd's next new release base on `emqx30` branch? I found the v5.2.2 some different to it, such as esockd's callbacks.

**Comment by Gilbert-Wong** [comment]
I create a rebar3 project and add dependency of emqx-3.0 branch esockd in it. There is no problem as you stated. This is my rebar3 config. Maybe it helps you solve this issue.

rebar3.config
```erlang
{erl_opts, [debug_info]}.
{deps, [
       {esockd, {git, "git@github.com:emqtt/esockd.git", {branch, "emqx30"}}}
]}.

{shell, [
% {config, [{config, "config/sys.config"}]},
{apps, [esockd_test]}
]}.

```
